### ISSUE TITLE
Issue with function get_predictor_classes

### ISSUE THREAD

**Issue by FelixR21** [ModelOriented/xspliner#87]
Hi I had a problem when running XSPLINE, the source is this function get_predictor_classes delivering error message:

Error: Result 1 is not a length 1 atomic vector

This is due to the line 
purrr::map_chr(1:ncol(data), function(x) class(data[,x]))

where class(data[,x]) in my case produces 
> class(data[,1])
[1] "tbl_df"     "tbl"        "data.frame"

A change to class(data[[x]]) fixes the problem 

I think this might be due to the data input type, but i can't see anything mandating a certain type of data. 

Cheers

Felix

**Comment by krystian8207** [comment]
Thank you @FelixR21 for reporting this. I'll try to check and fix the problem today.

**Comment by krystian8207** [comment]
@FelixR21 The issue is already solved. Please install the version from Github. I'd be grateful if you confirm it fixed your problem.
